[package]
name = "mem-agent-srv"
version = "0.1.0"
edition = "2021"

[dependencies]
slog = "2.5.2"
slog-scope = "4.1.2"
slog-term = "2.9.0"
slog-async = "2.7"
structopt = "0.3"
anyhow = "1.0"
libc = "0.2"

share = {path = "../../crates/share"}
mem-agent-lib = { path = "../../crates/mem-agent-lib" }
