[package]
name = "mem-agent-srv"
version = "0.2.0"
edition = "2021"

[dependencies]
slog-scope = "4.1.2"
slog-term = "2.9.0"
slog-async = "2.7"
structopt = "0.3"
anyhow = "1.0"
libc = "0.2"

share = {path = "../../crates/share"}
mem-agent-lib = { path = "../../crates/mem-agent-lib" }

[dependencies.slog]
version = "2.7"
features = ["release_max_level_trace", "max_level_trace"]
