[package]
name = "protocols"
version = "0.1.0"
edition = "2021"

[dependencies]
ttrpc = { version = "0.8", features = ["async"] }
tokio = { version = "1.33", features = ["full"] }
async-trait = "0.1"
byteorder = "1.5"
protobuf = "3.7"

[build-dependencies]
ttrpc-codegen = "0.5"
