[package]
name = "mem-agent-ctl"
version = "0.2.0"
edition = "2021"

[dependencies]
structopt = "0.3"
anyhow = "1.0"
libc = "0.2"
ttrpc = { version = "0.8", features = ["async"] }
tokio = { version = "1.33", features = ["full"] }

share = {path = "../../crates/share"}
protocols = {path = "../../crates/protocols"}
mem-agent-lib = { path = "../../crates/mem-agent-lib" }
